### ISSUE TITLE
multiple skipIfMatch regexes not working?

### ISSUE THREAD

**Issue by iilei** [aotaduy/eslint-plugin-spellcheck#29]
It seems passing multiple Regexes to skipIfMatch doesn't apply.

This is the related config (yaml) I have:

```yaml
    skipIfMatch:
    - ^\S[^aeiou]{1,3}$    # Intl, cldr
    - https?://[^s]*
```
more config, just in case:
````
  extends: "airbnb"
  root: true
  ecmaFeatures:
    jsx: true
    templateStrings: true
    classes: true
    modules: true
````

and something among the lines of

```js
const cldrDataByLang = [...cldrDataByLocale].reduce((map, [locale, data]) => { 
    /* ... omitted ... */
});
```
Results in
```bash
    3:29  error  You have a misspelled word: cldr on String      spellcheck/spell-checker
```

As 
```js
/^\S[^aeiou]{1,3}$/.test('cldr') === true;
```
I would expect this not to be considered a rule violation.
